[View in Colaboratory](https://colab.research.google.com/github/LuizFelipeLemon/machine_learning/blob/master/svm_multclass.ipynb)

In [0]:
# Support Vector Machine (SVM)
# from https://www.superdatascience.com/machine-learning/ 


# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn.metrics as m

In [0]:
import os
import tarfile
from six.moves import urllib

FILE_TO_DOWNLOAD =  "bla.csv"
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/GabrielVantuil/ECT2702-TAI/"
DATA_PATH = "master/"
DATA_URL = DOWNLOAD_ROOT + DATA_PATH + FILE_TO_DOWNLOAD

def fetch_data(data_url=DATA_URL, data_path=DATA_PATH, file_to_download=FILE_TO_DOWNLOAD):
  if not os.path.isdir(data_path):
    os.makedirs(data_path)
  urllib.request.urlretrieve(data_url, data_path+file_to_download)
  
  
fetch_data()

# observando se o diretório datasets foi criado com sucesso 

In [26]:
# Importing the dataset
dataset = pd.read_csv(DATA_PATH+FILE_TO_DOWNLOAD)


dataset.head(  )

R   G   B  cor
0  32  42  28    2
1  32  42  28    2
2  32  42  28    2
3  32  42  28    2
4  32  42  28    2

In [27]:
X = dataset.iloc[:,:3].values
y = dataset.iloc[:,3].values

noise = np.random.random_integers(-15, 15, size=(300, 3))
X = X + noise

#print(X)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: This function is deprecated. Please call randint(-15, 15 + 1) instead
  after removing the cwd from sys.path.


In [0]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [29]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [30]:
# Fitting SVM to the Training set
#from sklearn.svm import SVC
#classifier = SVC(kernel = 'linear', random_state = 0)
#classifier = SVC(decision_function_shape='ovo')

#classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [47]:
# Fitting SVM to the Training set
from sklearn.svm import SVC
#classifier = SVC(kernel = 'linear', random_state = 0)
classifier = SVC(decision_function_shape='ovo')

classifier.fit(X_train, y_train)

C_2d_range = np.logspace(-2,10,13)

gamma_2d_range = np.logspace(-9,3,13)



print(C_2d_range)
classifiers = []


for C in C_2d_range:
    for gamma in gamma_2d_range:
      
        classifier = SVC(C=C, gamma=gamma)
        classifier.fit(X_train, y_train)
        
        y_pred = classifier.predict(X_test)
        
        error = m.mean_squared_error(y_pred,y_test)
        
        
        classifiers.append((C, gamma, error))        
       
print(len(classifiers))


[1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07
 1.e+08 1.e+09 1.e+10]
169


In [52]:
classifiers.sort(key = lambda x:x[2], reverse = False)
print(classifiers)

[(100000000.0, 1e-08, 0.26666666666666666), (1000000000.0, 1e-08, 0.28), (10000000000.0, 1e-08, 0.28), (10000000000.0, 0.001, 0.30666666666666664), (10.0, 10.0, 0.3466666666666667), (100.0, 10.0, 0.3466666666666667), (1000.0, 10.0, 0.3466666666666667), (10000.0, 10.0, 0.3466666666666667), (100000.0, 10.0, 0.3466666666666667), (1000000.0, 10.0, 0.3466666666666667), (10000000.0, 1e-08, 0.3466666666666667), (10000000.0, 10.0, 0.3466666666666667), (100000000.0, 10.0, 0.3466666666666667), (1000000000.0, 10.0, 0.3466666666666667), (10000000000.0, 1e-06, 0.3466666666666667), (10000000000.0, 10.0, 0.3466666666666667), (1.0, 10.0, 0.37333333333333335), (100000000.0, 0.1, 0.37333333333333335), (1000000000.0, 0.1, 0.37333333333333335), (10000000000.0, 0.1, 0.37333333333333335), (10.0, 0.01, 0.38666666666666666), (100.0, 0.001, 0.38666666666666666), (1000.0, 0.0001, 0.38666666666666666), (1000.0, 0.001, 0.38666666666666666), (10000.0, 1e-05, 0.38666666666666666), (10000.0, 0.0001, 0.38666666666666

In [53]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

print(y_test[0:35])
print(y_pred[0:35])

[0 1 2 0 0 1 0 0 2 1 0 2 1 0 2 2 0 2 0 1 1 1 1 1 0 1 1 0 0 0 2 2 2 1 0]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [32]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[24  0  2]
 [ 1 20  4]
 [ 7  1 16]]


In [33]:
# Visualising the Training set results
from matplotlib.colors import ListedColormap
X_set, y_set = X_train, y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('blue', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('SVM (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

ValueError: ignored